# vars:
#   - params: ../params.yaml
#   - pipeline_name: pipeline1

stages:
  load_data:
    cmd: python src/stage_load_data.py --params=params.yaml
    params:
      - base
      - data_load
    deps:
      - src/stage_load_data.py

  prep_features:
    cmd: python src/stage_prep_features.py --params=params.yaml
    params:
      - base
      - data_load
      - data_condition
    deps:
      - src/features/create_xy.py
      - src/stage_prep_features.py
    outs:
      - data/train/X_train_sc.pkl
      - data/train/X_test_sc.pkl
      - data/train/X_train.pkl
      - data/train/X_test.pkl     
      - data/train/y_train.pkl
      - data/train/y_test.pkl
      - data/train/class_weights.json

  train_model:
    cmd: python src/stage_train_model.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
    deps:
      - data/train/X_train_sc.pkl
      - data/train/X_test_sc.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl
      - data/train/class_weights.json
      - src/model/train.py
      - src/stage_train_model.py
    outs:
      - models/model.joblib

  select_features_hyperparams:
    cmd: python src/stage_select_features.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
      - select
    deps:
      - data/train/X_train_sc.pkl
      - data/train/X_test_sc.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl
      - models/model.joblib
      - src/features/feature_selection.py
      - src/stage_select_features.py
    outs:
      - data/train/selected_features.csv

  evaluate_model:
    cmd: python src/stage_evaluate_model.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
      - evaluate
    deps:
      - data/train/X_test_sc.pkl 
      - data/train/y_test.pkl
      - models/model.joblib 
      - src/evaluation/validation_visuals.py
      - src/stage_evaluate_model.py
    metrics:
      - src/evaluation/metrics.json
    plots:
      - src/evaluation/confusion_matrix.png
      - src/evaluation/confusion_matrix_data.csv:
          template: confusion_normalized
          x: predicted
          y: y_true