stages:
  load_data:
    cmd: python src/stage_load_data.py --config=params.yaml
    deps:
      - src/stage_load_data.py
    params:
      - base
      - data_load

  prep_features:
    cmd: python src/stage_prep_features.py --config=params.yaml
    deps:
      - src/features/create_xy.py
      - src/stage_prep_features.py
    params:
      - base
      - data_load
      - data_condition
      - data_train
    outs:
      - data/train/X_train.pkl
      - data/train/X_test.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl

  train_model:
    cmd: python src/stage_train_model.py --config=params.yaml
    deps:
      - data/train/X_train.pkl
      - data/train/X_test.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl
      - data/train/X_train_selected.pkl # optional?
      - data/train/X_test_selected.pkl
      - reports/selected_feature_indicies.json
      - src/model/feature_selection.py
      - src/model/train.py
      - src/model/tune.py
      - src/stage_train_model.py
    params:
      - base
      - data_condition
      - train
      - tune
    outs:
      - models/model.joblib
      - models/model_fs.joblib
      - models/model_tuned.joblib
      - data/train/X_train_selected.pkl
      - data/train/X_test_selected.pkl
      - reports/selected_feature_indicies.json
      - reports/best_params.json

  evaluate_model:
    cmd: python src/stage_evaluate_model.py --config=params.yaml
    deps:
      - data/train/X_test_selected.pkl
      - data/train/X_test.pkl # this or above
      - data/train/y_test.pkl
      - models/model_tuned.joblib # this could vary?
      - src/reports/validation_visuals.py
      - src/stage_evaluate_model.py
    params:
      - base
      - data_condition
      - train
      - evaluate
    metrics:
      - src/reports/metrics.json

    plots:
      - src/reports/confusion_matrix.png
      - src/reports/confusion_matrix_data.csv:
          template: confusion_normalized
          x: predicted
          y: y_true