stages:
  # load_data:
  #   cmd: python src/stage_load_data.py --params=params.yaml
  #   deps:
  #     - src/stage_load_data.py
  #   params:
  #     - base
  #     - data_load

  prep_features:
    cmd: python src/stage_prep_features.py --params=params.yaml
    deps:
      - src/features/create_xy.py
      - src/stage_prep_features.py
    params:
      - base
      - data_load
      - data_condition
      - train
    outs:
      - data/train/X_train.pkl
      - data/train/X_test.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl

  train_model:
    cmd: python src/stage_train_model.py --params=params.yaml
    deps:
      - data/train/X_train.pkl
      - data/train/X_test.pkl
      - data/train/y_train.pkl
      - data/train/y_test.pkl
      - src/model/feature_selection.py
      - src/model/train.py
      - src/model/tune.py
      - src/stage_train_model.py
    params:
      - base
      - data_condition
      - train
      - tune
    outs:
      - models/model.joblib
      - data/train/selected_features.json
      - src/evaluation/best_params.json

  evaluate_model:
    cmd: python src/stage_evaluate_model.py --params=params.yaml
    deps:
      - data/train/X_test.pkl 
      - data/train/y_test.pkl
      - models/model.joblib 
      - src/evaluation/validation_visuals.py
      - src/stage_evaluate_model.py
    params:
      - base
      - data_condition
      - train
      - evaluate
    metrics:
      - src/evaluation/metrics.json
      #cache: false  # keep as part of git history

    plots:
      - src/evaluation/confusion_matrix.png
      - src/evaluation/confusion_matrix_data.csv:
          template: confusion_normalized
          x: predicted
          y: y_true