# vars:
#   - params: ../params.yaml
#   - pipeline_name: pipeline1

stages:
  load_data:
    cmd: python src/stage_load_data.py --params=params.yaml
    params:
      - base
      - data_load
    deps:
      - src/stage_load_data.py

  prep_features:
    cmd: python src/stage_prep_features.py --params=params.yaml
    params:
      - base
      - data_load
      - data_condition
    deps:
      - src/features/create_xy.py
      - src/stage_prep_features.py
    outs:
      - ${data_condition.X_train}:
          persist: True
      - ${data_condition.X_train_scaled}:
          persist: True
      - ${data_condition.X_test_scaled}:
          persist: True
      - ${data_condition.X_test}:
          persist: True
      - ${data_condition.y_train}:
          persist: True
      - ${data_condition.y_test}:
          persist: True
      - ${data_condition.class_weights}:
          persist: True

  select_features_hyperparams:
    cmd: python src/stage_select_and_tune.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
      - select
    deps:
      - ${data_condition.X_train}
      - ${data_condition.X_train_scaled}
      - ${data_condition.X_test_scaled}
      - ${data_condition.X_test}
      - ${data_condition.y_train}
      - ${data_condition.y_test}
      - ${data_condition.class_weights}
      - src/features/feature_selection.py
    outs:
      - ${select.selected_features_path}
      - ${select.X_train_selected}
      - ${select.X_test_selected}
      - ${tune.best_params}

  train_model:
    cmd: python src/stage_train_model.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
    deps:
      - ${data_condition.y_train}
      - ${data_condition.y_test}
      - ${select.selected_features_path}
      - ${select.X_train_selected}
      - ${select.X_test_selected}
      - ${tune.best_params}
      - ${data_condition.class_weights}
      - src/model/train.py
      - src/stage_train_model.py
    outs:
      - ${train.model_name}

  evaluate_model:
    cmd: python src/stage_evaluate_model.py --params=params.yaml
    params:
      - base
      - data_condition
      - train
      - evaluate
    deps:
      - ${data_condition.y_test}
      - ${train.model_name}
      - src/evaluation/validation_visuals.py
      - src/stage_evaluate_model.py
    metrics:
      - src/evaluation/metrics.json
    plots:
      - src/evaluation/confusion_matrix.png
      - src/evaluation/confusion_matrix_data.csv:
          template: confusion_normalized
          x: predicted
          y: y_true
