base:
  log_level: INFO
  random_state: 121

data_load:
  download_data: False
  sso_profile_name: 'rognstad-dev'
  bucket_name: 'restoration-monitoring'
  folder_prefix: 'plantation-mapping/data/train/'
  local_prefix: 'data/train/'
  summary_filename: 'data/Training_Data.xlsx'
  summary_sheetname: 'CEO_Surveys'
  survey_id_column_name: 'CEO Survey'
  ceo_survey_directory: 'data/ceo-surveys'
  data_prefix_list:
    - slope
    - s1
    - s2
    - dem
    - features-ckpt-2023-02-09
    - labels
  ceo_json: 'src/report/ceo_list.json'
  report_output_dir: /report/
  
data_condition:
  train_filter_features:
#    Country: ghana
    Use?: 'yes'
    Classes: multi
  label_cats:
    Monoculture: 1
    Agroforestry: 2
    Not plantation: 0
    Unknown: 255
  scale_features: True

train: 
  cv: 3
  estimator_name: cat
  max_features: 40
  metric: rmse
  estimators:
    rfc: #sklearn.ensemble.RandomForestClassifier
      importance_metric: shap
      use_class_weights: True
      param_grid:
    svm:
      importance_metric: shap
      use_class_weights: True
      param_grid:
    lgbm:
      importance_metric: shap
      use_class_weights: True 
      param_grid:
    xgb:
      importance_metric: shap 
      use_class_weights: True
      param_grid:
    cat: 
      importance_metric: shap
      param_grid:
    logreg:
      importance_metric: shap
      use_class_weights: True
      param_grid:
  model_path: ../models/model.joblib

