base:
  log_level: DEBUG
  random_state: 121
  config: config.yaml

data_load:
  download_data: false
  bucket_name: restoration-monitoring
  folder_prefix: plantation-mapping/data/train/
  local_prefix: data/
  ceo_survey:
    - v08
    # - v14
    - v15
    - v18
    - v19
    - v20
  data_prefix_list:
    - slope
    - s1
    - s2
    - dem
    - features-ckpt-2023-02-09
    - labels
    - ard
    - features-ard

data_condition:
  select_features: True
  selected_features: data/train/selected_features.json
  classes: 4
  ard_subsample: 4
  subset_fraction: 0.10 # set to 1.0 for all data
  test_split: 20
  train_split: 80
  val_split: 25
  X_train: data/train/X_train.pkl
  y_train: data/train/y_train.pkl
  X_test: data/train/X_test.pkl
  y_test: data/train/y_test.pkl

train:
  model_name: model
  perform_fs: True #this will also trigger scaling
  tune_hyperparams: True
  max_features: 40 # number of feats to use in feature selection
  estimator_name: cat
  cv: 3
  tuning_metric: balanced_accuracy
  testing_metrics: accuracy balanced_accuracy precision recall f1 roc_auc log_loss
  estimators:
    rfc: #sklearn.ensemble.RandomForestClassifier
      importance_metric: shap
      use_class_weights: true
      param_grid:
    svm:
      importance_metric: shap
      use_class_weights: true
      param_grid:
    lgbm:
      importance_metric: shap
      use_class_weights: true
      param_grid:
    xgb:
      importance_metric: shap
      use_class_weights: true
      param_grid:
    logreg:
      importance_metric: shap
      use_class_weights: true
      param_grid:
    cat:
      importance_metric: shap
      use_class_weights: true
      use_defaults: true
      param_grid:
        loss_function: MultiClass
        random_state: 121
        # iterations: 811         #default is 500
        # depth: 10               #default is 6
        # 12_leaf_reg: 11         #default is 3
        # min_data_in_leaf: 50    #default is 1
        # learning_rate: 0.04       #default is 0.1007
        logging_level: Silent
  model_dir: models/

tune:
  # use_fs_data: True
  estimator_name: cat
  n_iter: 5 #num of parameter settings that are sampled
  cv: 3
  plot: False
  verbose: False
  estimators:
    cat:
      param_grid:
        iter_min: 500
        iter_max: 1200
        iter_step: 10
        depth_min: 6
        depth_max: 12
        depth_step: 4
        leaf_reg_min: 2
        leaf_reg_max: 30
        leaf_reg_step: 4
        min_data_leaf_min: 20
        min_data_leaf_max: 100
        min_data_leaf_step: 3
        learn_rate:
          - .02
          - .03
          - .04
  best_params: src/evaluation/best_params.json

evaluate:
  # migrate to -- folder_prefix: src/evaluation
  metrics_file: src/evaluation/metrics.json
  confusion_matrix_image: src/evaluation/confusion_matrix.png
  confusion_matrix_data: src/evaluation/confusion_matrix_data.csv
  tile_id_loc: data
  tile_s3_bucket: tof-output
