base:
  log_level: DEBUG
  random_state: 121
  config: config.yaml

deploy:
  verbose: false
  data_dir: data/
  bucket: tof-output
  model_path: models/model.joblib
  model_type: classifier
  remove_noise: true
  cleanup: false
  overwrite: false
  version: v26_2

data_load:
  download_data: false
  bucket_name: restoration-monitoring
  folder_prefix: plantation-mapping/data/train/
  local_prefix: data/
  ttc_feats_dir: train-features-ard/
  create_labels: false
  ceo_survey:
    - v08
    - v14
    - v15
    - v19
    - v20
    - v21
    - v22

data_condition:
  total_feature_count: 94
  classes: 4
  ard_subsample: 4
  subset_fraction: 0.1 # set to 1.0 for all data
  test_split: 20 
  train_split: 80
  val_split: 25
  modelData_path: data/train_params/modelData.pkl

select:
  select_features: False       # Update
  max_features: 40
  selected_features_path: data/train_params/selected_features.json

tune:
  tune_hyperparameters: True   # Update
  n_iter: 25
  cv: 3
  plot: False
  verbose: False
  estimators:
    cat:
      param_grid:
        iter_min: 600
        iter_max: 1300
        iter_step: 200
        depth_min: 6
        depth_max: 12
        depth_step: 4
        leaf_reg_min: 2
        leaf_reg_max: 30
        leaf_reg_step: 4
        min_data_leaf_min: 800
        min_data_leaf_max: 3000
        min_data_leaf_step: 6
        learn_rate:
          - .02
          - .03
          - .04
          - .05
  best_params: data/train_params/best_params.json

train:
  use_best_params: False        # Update
  model_dir: models/ 
  model_name: models/model.joblib
  estimator_name: cat
  cv: 3
  tuning_metric: balanced_accuracy
  testing_metrics: accuracy balanced_accuracy precision recall f1 roc_auc log_loss
  estimators:
    cat:
      use_class_weights: true
      param_grid:
        loss_function: MultiClass
        random_state: 121
        logging_level: Silent 
        depth: 10
        iterations: 900
        l2_leaf_reg: 11
        min_data_in_leaf: 120
        learning_rate: 0.05   
        # early_stopping_rounds: 10

evaluate:
  metrics_file: src/evaluation/metrics
  cm_image: src/evaluation/confusion_matrix
  cm_data: src/evaluation/confusion_matrix_data
  train_progress: src/evaluation/train_progress
  tile_id_loc: data


