vars:
  - params: ../params.yaml
  - pipeline_name: pipeline3

stages:
  train_model:
    cmd: python ../src/stage_train_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
    deps:
      - ../data/train/X_train_fs.pkl
      - ../data/train/X_test_fs.pkl
      - ../data/train/y_train_fs.pkl
      - ../data/train/y_test_fs.pkl
      - ../src/model/train.py
      - ../src/stage_train_model.py
    outs:
      - ../models/model_p3.joblib

  evaluate_model:
    cmd: python ../src/stage_evaluate_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
        - evaluate
    deps:
      - ../data/train/X_test_fs.pkl 
      - ../data/train/y_test_fs.pkl
      - ../models/model_p3.joblib 
      - ../src/evaluation/validation_visuals.py
      - ../src/stage_evaluate_model.py
    metrics:
      - ../src/evaluation/metrics_p3.json
      #cache: false  # keep as part of git history
    plots:
      - ../src/evaluation/confusion_matrix_p3.png
      - ../src/evaluation/confusion_matrix_data_p3.csv:
          template: confusion_normalized
          x: predicted
          y: y_true