vars:
  - params: ../params.yaml
  - pipeline_name: pipeline3

stages:
  prep_features:
    cmd: python ../src/stage_prep_features.py --params=${params}
    params:
      - ${params}:
        - base
        - data_load
        - data_condition
        - train
    deps:
      - ../src/features/create_xy.py
      - ../src/stage_prep_features.py
    outs:
      - ../data/train/X_train.pkl
      - ../data/train/X_test.pkl
      - ../data/train/y_train.pkl
      - ../data/train/y_test.pkl
      - ../data/train/class_weights.json

  train_model:
    cmd: python ../src/stage_train_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
    deps:
      - ../data/train/X_train.pkl
      - ../data/train/X_test.pkl
      - ../data/train/y_train.pkl
      - ../data/train/y_test.pkl
      - ../src/model/train.py
      - ../src/stage_train_model.py
    outs:
      - ../models/model.joblib

  evaluate_model:
    cmd: python ../src/stage_evaluate_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
        - evaluate
    deps:
      - ../data/train/X_test.pkl 
      - ../data/train/y_test.pkl
      - ../models/model.joblib 
      - ../src/evaluation/validation_visuals.py
      - ../src/stage_evaluate_model.py
    metrics:
      - ../src/evaluation/metrics.json
      #cache: false  # keep as part of git history
    plots:
      - ../src/evaluation/confusion_matrix.png
      - ../src/evaluation/confusion_matrix_data.csv:
          template: confusion_normalized
          x: predicted
          y: y_true