vars:
  - params: ../params.yaml
  - pipeline_name: pipeline1

stages:
  load_data:
    cmd: python ../src/stage_load_data.py --params=${params}
    params:
      - ${params}:
        - base
        - data_load
    deps:
      - ../src/stage_load_data.py

  prep_features:
    cmd: python ../src/stage_prep_features.py --params=${params}
    params:
      - ${params}:
        - base
        - data_load
        - data_condition
    deps:
      - ../src/features/create_xy.py
      - ../src/stage_prep_features.py
    outs:
      - ../data/train/X_train_scaled.pkl:
          persist: true
      - ../data/train/X_test_scaled.pkl:
          persist: true
      - ../data/train/y_train_scaled.pkl:
          persist: true
      - ../data/train/y_test_scaled.pkl:
          persist: true
      - ../data/train/class_weights_p1.json:
          persist: true

  train_model:
    cmd: python ../src/stage_train_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
    deps:
      - ../data/train/X_train_scaled.pkl
      - ../data/train/X_test_scaled.pkl
      - ../data/train/y_train_scaled.pkl
      - ../data/train/y_test_scaled.pkl
      - ../data/train/class_weights_p1.json
      - ../src/model/train.py
      - ../src/stage_train_model.py
    outs:
      - ../models/model_p1.joblib:
          persist: true

  select_features:
    cmd: python ../src/stage_select_features.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
        - select
    deps:
      - ../data/train/X_train_scaled.pkl
      - ../data/train/X_test_scaled.pkl
      - ../data/train/y_train_scaled.pkl
      - ../data/train/y_test_scaled.pkl
      - ../models/model_p1.joblib
      - ../src/features/feature_selection.py
      - ../src/stage_select_features.py
    outs:
      - ../data/train/selected_features.csv:
          persist: true

  evaluate_model:
    cmd: python ../src/stage_evaluate_model.py --params=${params}
    params:
      - ${params}:
        - base
        - data_condition
        - train
        - evaluate
    deps:
      - ../data/train/X_test_scaled.pkl 
      - ../data/train/y_test_scaled.pkl
      - ../models/model_p1.joblib 
      - ../src/evaluation/validation_visuals.py
      - ../src/stage_evaluate_model.py
    metrics:
      - ../src/evaluation/metrics_p1.json
    plots:
      - ../src/evaluation/confusion_matrix_p1.png
      - ../src/evaluation/confusion_matrix_data_p1.csv:
          template: confusion_normalized
          x: predicted
          y: y_true